import { GrafanaItem } from "./GrafanaItem.js";
import { Annotations } from "./Annotations.js";
import { Link } from "./Link.js";
import { Panel } from "./Panel.js";
import { Templating } from "./Templating.js";
import { TimeRange } from "./TimeRange.js";
import { TimePicker } from "./TimePicker.js";

import type { GenericMetaOptions } from "@gdacm/base-types";

export declare class Dashboard extends GrafanaItem {
    setAnnotations(annotations: Annotations): this;
    setNewAnnotations(onNewCreated: ((item: Annotations) => Annotations) | undefined): this;
    withAnnotations(onWith: (item: Annotations) => void): this;
    get annotations(): Annotations;
    get editable(): Boolean;
    setEditable(editable: Boolean): this;
    get fiscalYearStartMonth(): Number;
    setFiscalYearStartMonth(fiscalYearStartMonth: Number): this;
    get graphTooltip(): Number;
    setGraphTooltip(graphTooltip: Number): this;
    initLinks(): this;
    get links(): Link[];
    addLink(link: Link): this;
    addNewLink(onNewCreated: (item: Link) => Link): this;
    withLinks(onWith: (links: Link[]) => void): this;
    get liveNow(): Boolean;
    setLiveNow(liveNow: Boolean): this;
    initPanels(): this;
    get panels(): Panel[];
    addPanel(panel: Panel): this;
    addNewPanel(onNewCreated: (item: Panel) => Panel): this;
    withPanels(onWith: (panels: Panel[]) => void): this;
    get preload(): Boolean;
    setPreload(preload: Boolean): this;
    get schemaVersion(): Number;
    setSchemaVersion(schemaVersion: Number): this;
    get refresh(): String;
    setRefresh(refresh: String): this;
    get tags(): Array<String>;
    setTags(tags: Array<String>): this;
    setTemplating(templating: Templating): this;
    setNewTemplating(onNewCreated: ((item: Templating) => Templating) | undefined): this;
    withTemplating(onWith: (item: Templating) => void): this;
    get templating(): Templating;
    setTime(time: TimeRange): this;
    setNewTime(onNewCreated: ((item: TimeRange) => TimeRange) | undefined): this;
    withTime(onWith: (item: TimeRange) => void): this;
    get time(): TimeRange;
    setTimeRange(from: string, to: string): this;
    setTimepicker(timepicker: TimePicker): this;
    setNewTimepicker(onNewCreated: ((item: TimePicker) => TimePicker) | undefined): this;
    withTimepicker(onWith: (item: TimePicker) => void): this;
    get timepicker(): TimePicker;
    get timezone(): String;
    setTimezone(timezone: String): this;
    get title(): String;
    setTitle(title: String): this;
    get uid(): String;
    setUid(uid: String): this;
}
