import { FieldConfigCustom } from "./FieldConfigCustom.js";
import { ScaleDistribution } from "./ScaleDistribution.js";
import { HideFrom } from "./HideFrom.js";
import { LineStyle } from "./LineStyle.js";
import { Stacking } from "./Stacking.js";
import { ThresholdStyle } from "./ThresholdStyle.js";

import type { GenericMetaOptions } from "@gdacm/base-types";

export declare class FieldConfigCustomTimeSerie extends FieldConfigCustom {
    get axisBorderShow(): Boolean;
    setAxisBorderShow(axisBorderShow: Boolean): this;
    get axisCenteredZero(): Boolean;
    setAxisCenteredZero(axisCenteredZero: Boolean): this;
    get axisColorMode(): String;
    setAxisColorMode(axisColorMode: String): this;
    get axisGridShow(): Boolean;
    setAxisGridShow(axisGridShow: Boolean): this;
    get axisLabel(): String;
    setAxisLabel(axisLabel: String): this;
    get axisPlacement(): String;
    setAxisPlacement(axisPlacement: String): this;
    get axisSoftMax(): Number;
    setAxisSoftMax(axisSoftMax: Number): this;
    get axisSoftMin(): Number;
    setAxisSoftMin(axisSoftMin: Number): this;
    get axisWidth(): Number;
    setAxisWidth(axisWidth: Number): this;
    setScaleDistribution(scaleDistribution: ScaleDistribution): this;
    setNewScaleDistribution(onNewCreated: ((item: ScaleDistribution) => ScaleDistribution) | undefined): this;
    withScaleDistribution(onWith: (item: ScaleDistribution) => void): this;
    get scaleDistribution(): ScaleDistribution;
    get barAlignment(): Number;
    setBarAlignment(barAlignment: Number): this;
    get barMaxWidth(): Number;
    setBarMaxWidth(barMaxWidth: Number): this;
    get barWidthFactor(): Number;
    setBarWidthFactor(barWidthFactor: Number): this;
    get drawStyle(): String;
    setDrawStyle(drawStyle: String): this;
    get fillBelowTo(): String;
    setFillBelowTo(fillBelowTo: String): this;
    get fillColor(): String;
    setFillColor(fillColor: String): this;
    get fillOpacity(): Number;
    setFillOpacity(fillOpacity: Number): this;
    get gradientMode(): String;
    setGradientMode(gradientMode: String): this;
    setHideFrom(hideFrom: HideFrom): this;
    setNewHideFrom(onNewCreated: ((item: HideFrom) => HideFrom) | undefined): this;
    withHideFrom(onWith: (item: HideFrom) => void): this;
    get hideFrom(): HideFrom;
    get insertNulls(): Boolean;
    setInsertNulls(insertNulls: Boolean): this;
    get lineInterpolation(): String;
    setLineInterpolation(lineInterpolation: String): this;
    setLineStyle(lineStyle: LineStyle): this;
    setNewLineStyle(onNewCreated: ((item: LineStyle) => LineStyle) | undefined): this;
    withLineStyle(onWith: (item: LineStyle) => void): this;
    get lineStyle(): LineStyle;
    setLineStyleFill(fill: string): this;
    get lineWidth(): Number;
    setLineWidth(lineWidth: Number): this;
    get pointColor(): String;
    setPointColor(pointColor: String): this;
    get pointSize(): Number;
    setPointSize(pointSize: Number): this;
    get pointSymbol(): String;
    setPointSymbol(pointSymbol: String): this;
    get showPoints(): String;
    setShowPoints(showPoints: String): this;
    get showValues(): Boolean;
    setShowValues(showValues: Boolean): this;
    get spanNulls(): Boolean;
    setSpanNulls(spanNulls: Boolean): this;
    setStacking(stacking: Stacking): this;
    setNewStacking(onNewCreated: ((item: Stacking) => Stacking) | undefined): this;
    withStacking(onWith: (item: Stacking) => void): this;
    get stacking(): Stacking;
    setThresholdsStyle(thresholdsStyle: ThresholdStyle): this;
    setNewThresholdsStyle(onNewCreated: ((item: ThresholdStyle) => ThresholdStyle) | undefined): this;
    withThresholdsStyle(onWith: (item: ThresholdStyle) => void): this;
    get thresholdsStyle(): ThresholdStyle;
    setThresholdsStyleMode(mode: string): this;
}
