import { GrafanaItem } from "./GrafanaItem.js";
import { Datasource } from "./Datasource.js";
import { FieldConfig } from "./FieldConfig.js";
import { GridPos } from "./GridPos.js";
import { Link } from "./Link.js";
import { Target } from "./Target.js";
import { DataTransformation } from "./DataTransformation.js";

import type { GenericMetaOptions } from "@gdacm/base-types";

export declare class Panel extends GrafanaItem {
    get cacheTimeout(): String;
    setCacheTimeout(cacheTimeout: String): this;
    setDatasource(datasource: Datasource): this;
    setNewDatasource(onNewCreated: ((item: Datasource) => Datasource) | undefined): this;
    withDatasource(onWith: (item: Datasource) => void): this;
    get datasource(): Datasource;
    get description(): String;
    setDescription(description: String): this;
    setFieldConfig(fieldConfig: FieldConfig): this;
    setNewFieldConfig(onNewCreated: ((item: FieldConfig) => FieldConfig) | undefined): this;
    withFieldConfig(onWith: (item: FieldConfig) => void): this;
    get fieldConfig(): FieldConfig;
    setGridPos(gridPos: GridPos): this;
    setNewGridPos(onNewCreated: ((item: GridPos) => GridPos) | undefined): this;
    withGridPos(onWith: (item: GridPos) => void): this;
    get gridPos(): GridPos;
    setPos(x: number, y: number, w: number, h: number): this;
    get hideTimeOverride(): Boolean;
    setHideTimeOverride(hideTimeOverride: Boolean): this;
    get id(): Number;
    setId(id: Number): this;
    get interval(): String;
    setInterval(interval: String): this;
    initLinks(): this;
    get links(): Link[];
    addLink(link: Link): this;
    addNewLink(onNewCreated: (item: Link) => Link): this;
    withLinks(onWith: (links: Link[]) => void): this;
    get maxDataPoints(): Number;
    setMaxDataPoints(maxDataPoints: Number): this;
    get maxPerRow(): Number;
    setMaxPerRow(maxPerRow: Number): this;
    setOptions(options: Object): this;
    setNewOptions(onNewCreated: ((item: Object) => Object) | undefined): this;
    withOptions(onWith: (item: Object) => void): this;
    get options(): Object;
    get pluginVersion(): String;
    setPluginVersion(pluginVersion: String): this;
    get queryCachingTTL(): Number;
    setQueryCachingTTL(queryCachingTTL: Number): this;
    get repeat(): String;
    setRepeat(repeat: String): this;
    get repeatDirection(): String;
    setRepeatDirection(repeatDirection: String): this;
    initTargets(): this;
    get targets(): Target[];
    addTarget(target: Target): this;
    addNewTarget(onNewCreated: (item: Target) => Target): this;
    withTargets(onWith: (targets: Target[]) => void): this;
    addTargetWithParams(refId: string, query: string, datasource: Datasource): this;
    get timeFrom(): String;
    setTimeFrom(timeFrom: String): this;
    get timeShift(): String;
    setTimeShift(timeShift: String): this;
    initTransformations(): this;
    get transformations(): DataTransformation[];
    addTransformation(transformation: DataTransformation): this;
    addNewTransformation(onNewCreated: (item: DataTransformation) => DataTransformation): this;
    withTransformations(onWith: (transformations: DataTransformation[]) => void): this;
    get type(): String;
    setType(type: String): this;
    get title(): String;
    setTitle(title: String): this;
}
