import { Target } from "./Target.js";
import { CsvWave } from "./CsvWave.js";
import { NodesQuery } from "./NodesQuery.js";
import { PulseWaveQuery } from "./PulseWaveQuery.js";
import { SimulationQuery } from "./SimulationQuery.js";
import { StreamingQuery } from "./StreamingQuery.js";
import { UsaQuery } from "./UsaQuery.js";

import type { GenericMetaOptions } from "@gdacm/base-types";

export declare class TargetTestDataQuery extends Target {
    get alias(): String;
    setAlias(alias: String): this;
    get channel(): String;
    setChannel(channel: String): this;
    get csvContent(): String;
    setCsvContent(csvContent: String): this;
    get csvFileName(): String;
    setCsvFileName(csvFileName: String): this;
    initCsvWave(): this;
    get csvWave(): CsvWave[];
    addCsvWaveItem(csvWaveItem: CsvWave): this;
    addNewCsvWaveItem(onNewCreated: (item: CsvWave) => CsvWave): this;
    withCsvWave(onWith: (csvWave: CsvWave[]) => void): this;
    get dropPercent(): Number;
    setDropPercent(dropPercent: Number): this;
    get errorSource(): String;
    setErrorSource(errorSource: String): this;
    get errorType(): String;
    setErrorType(errorType: String): this;
    get flamegraphDiff(): Boolean;
    setFlamegraphDiff(flamegraphDiff: Boolean): this;
    get labels(): String;
    setLabels(labels: String): this;
    get levelColumn(): Boolean;
    setLevelColumn(levelColumn: Boolean): this;
    get lines(): Number;
    setLines(lines: Number): this;
    get max(): Number;
    setMax(max: Number): this;
    get min(): Number;
    setMin(min: Number): this;
    get noise(): Number;
    setNoise(noise: Number): this;
    setNodes(nodes: NodesQuery): this;
    setNewNodes(onNewCreated: ((item: NodesQuery) => NodesQuery) | undefined): this;
    withNodes(onWith: (item: NodesQuery) => void): this;
    get nodes(): NodesQuery;
    setPulseWave(pulseWave: PulseWaveQuery): this;
    setNewPulseWave(onNewCreated: ((item: PulseWaveQuery) => PulseWaveQuery) | undefined): this;
    withPulseWave(onWith: (item: PulseWaveQuery) => void): this;
    get pulseWave(): PulseWaveQuery;
    get rawFrameContent(): String;
    setRawFrameContent(rawFrameContent: String): this;
    get scenarioId(): String;
    setScenarioId(scenarioId: String): this;
    get seriesCount(): Number;
    setSeriesCount(seriesCount: Number): this;
    setSim(sim: SimulationQuery): this;
    setNewSim(onNewCreated: ((item: SimulationQuery) => SimulationQuery) | undefined): this;
    withSim(onWith: (item: SimulationQuery) => void): this;
    get sim(): SimulationQuery;
    get spanCount(): Number;
    setSpanCount(spanCount: Number): this;
    get spread(): Number;
    setSpread(spread: Number): this;
    get startValue(): Number;
    setStartValue(startValue: Number): this;
    setStream(stream: StreamingQuery): this;
    setNewStream(onNewCreated: ((item: StreamingQuery) => StreamingQuery) | undefined): this;
    withStream(onWith: (item: StreamingQuery) => void): this;
    get stream(): StreamingQuery;
    get stringInput(): String;
    setStringInput(stringInput: String): this;
    setUsa(usa: UsaQuery): this;
    setNewUsa(onNewCreated: ((item: UsaQuery) => UsaQuery) | undefined): this;
    withUsa(onWith: (item: UsaQuery) => void): this;
    get usa(): UsaQuery;
    get withNil(): Boolean;
    setWithNil(withNil: Boolean): this;
}
