name: Publish & Deploy

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_REF: ${{ github.ref }}
      GH_REF_NAME: ${{ github.ref_name }}
      GH_EVENT_NAME: ${{ github.event_name }}
      INFLUXDBUID: ${{ secrets.INFLUXDBUID }}
      JSONDSUID: ${{ secrets.JSONDSUID }}
      HOST_GRA: ${{ vars.HOST_GRA }}
      TOKEN_GRA: ${{ secrets.TOKEN_GRA }}
    steps:
      - name: Get source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Inject Yarn npm scope auth at runtime
        run: |
          cat << 'EOF' >> .yarnrc.yml
          npmScopes:
            gdacm:
              npmAlwaysAuth: true
              npmAuthToken: "${NPM_TOKEN:-}"
          EOF

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:run

      - name: Run publish & deploy (${GH_REF}) (${GH_EVENT_NAME})
        run: |
          mkdir -p local
          cat << EOF > local/gra.json
          {
            "influxdbUid": "${INFLUXDBUID}",
            "jsonDsUid": "${JSONDSUID}"
          }
          EOF
          if [[ "${GH_REF}" == refs/tags/* ]]; then
            export GDM_TEST_NAME="t-${GH_REF_NAME}"
          else
            if [ "${GH_REF_NAME}" != "main" ]; then
              export GDM_TEST_NAME="b-${GH_REF_NAME}"
            fi
          fi
          echo "GDM_TEST_NAME=${GDM_TEST_NAME}"
          GDM_API_URL="${HOST_GRA}" GDM_API_TOKEN="${TOKEN_GRA}" GDM_INCLUDE="gra" yarn start

      - name : Publish NPM on Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn publishAll
